schema: lib/graphql/type-defs.graphqls
documents: '**/*.graphql'
plugins:
  - typescript
  - typescript-operations
  - typescript-react-apollo
  - typescript-resolvers
config:
  defaultMapper: Partial<{T}>
respectGitIgnore: true
